"""
CUET BMES Mystery Box Question Bank
Curated MCQs from the official examination and practice worksheet.
Categorized into: Easy, Medium, and Hard.
"""

SAMPLE_QUESTIONS = [
    # ==================== EASY LEVEL (Part 1: Conceptual & Bio Sciences) ====================
    {
        "question_text": "What is the SI unit of electric current?",
        "option_a": "Volt (V)",
        "option_b": "Ampere (A)",
        "option_c": "Ohm (Ω)",
        "option_d": "Watt (W)",
        "correct_option": "B",
        "category": "Electrical & Physics",
        "difficulty": "Easy",
        "explanation": "The SI base unit of electric current is the Ampere (A)."
    },
    {
        "question_text": "What is the SI unit of voltage (electrical potential difference)?",
        "option_a": "Volt (V)",
        "option_b": "Coulomb (C)",
        "option_c": "Ampere (A)",
        "option_d": "Joule (J)",
        "correct_option": "A",
        "category": "Electrical & Physics",
        "difficulty": "Easy",
        "explanation": "Voltage is measured in Volts (V), equivalent to Joules per Coulomb."
    },
    {
        "question_text": "What is the SI unit of electrical resistance?",
        "option_a": "Siemens",
        "option_b": "Ohm (Ω)",
        "option_c": "Henry",
        "option_d": "Farad",
        "correct_option": "B",
        "category": "Electrical & Physics",
        "difficulty": "Easy",
        "explanation": "Electrical resistance is measured in Ohms (Ω)."
    },
    {
        "question_text": "What is the SI unit of electrical power?",
        "option_a": "Joule",
        "option_b": "Watt (W)",
        "option_c": "Newton",
        "option_d": "Pascal",
        "correct_option": "B",
        "category": "Electrical & Physics",
        "difficulty": "Easy",
        "explanation": "Power is the rate of energy transfer, measured in Watts (1 W = 1 J/s)."
    },
    {
        "question_text": "What is the commercial billing unit of electrical energy on an electricity bill?",
        "option_a": "Kilowatt-hour (kWh)",
        "option_b": "Ampere-hour (Ah)",
        "option_c": "Megawatt (MW)",
        "option_d": "Volt-Ampere (VA)",
        "correct_option": "A",
        "category": "Electrical & Physics",
        "difficulty": "Easy",
        "explanation": "1 Unit on an electricity bill equals 1 Kilowatt-hour (1 kWh = 3.6 × 10^6 J)."
    },
    {
        "question_text": "What does AC stand for in electrical circuits?",
        "option_a": "Active Current",
        "option_b": "Alternating Current",
        "option_c": "Amplified Current",
        "option_d": "Apparent Current",
        "correct_option": "B",
        "category": "Electrical & Physics",
        "difficulty": "Easy",
        "explanation": "AC stands for Alternating Current."
    },
    {
        "question_text": "What does DC stand for in electronics?",
        "option_a": "Direct Current",
        "option_b": "Dynamic Charge",
        "option_c": "Digital Current",
        "option_d": "Dual Conductor",
        "correct_option": "A",
        "category": "Electrical & Physics",
        "difficulty": "Easy",
        "explanation": "DC stands for Direct Current."
    },
    {
        "question_text": "What is the primary function of an electrical transformer?",
        "option_a": "Convert AC to DC",
        "option_b": "Change AC voltage levels (step-up or step-down)",
        "option_c": "Store electric charge",
        "option_d": "Generate mechanical rotation",
        "correct_option": "B",
        "category": "Electrical & Physics",
        "difficulty": "Easy",
        "explanation": "Transformers step up or step down AC voltages using electromagnetic induction."
    },
    {
        "question_text": "What does a step-up transformer do to voltage and current?",
        "option_a": "Increases voltage and decreases current",
        "option_b": "Decreases voltage and increases current",
        "option_c": "Increases both voltage and current",
        "option_d": "Keeps voltage constant while increasing frequency",
        "correct_option": "A",
        "category": "Electrical & Physics",
        "difficulty": "Easy",
        "explanation": "A step-up transformer increases secondary voltage while proportionally decreasing secondary current."
    },
    {
        "question_text": "What is the energy conversion in an electric motor?",
        "option_a": "Mechanical energy to Electrical energy",
        "option_b": "Electrical energy to Mechanical energy",
        "option_c": "Thermal energy to Electrical energy",
        "option_d": "Chemical energy to Kinetic energy",
        "correct_option": "B",
        "category": "Electrical & Physics",
        "difficulty": "Easy",
        "explanation": "Electric motors convert electrical energy into mechanical rotational motion."
    },
    {
        "question_text": "What is the energy conversion in an electric generator (alternator)?",
        "option_a": "Electrical energy to Magnetic energy",
        "option_b": "Mechanical energy to Electrical energy",
        "option_c": "Chemical energy to Light energy",
        "option_d": "Heat energy to Nuclear energy",
        "correct_option": "B",
        "category": "Electrical & Physics",
        "difficulty": "Easy",
        "explanation": "Generators convert mechanical work into electrical energy."
    },
    {
        "question_text": "What is the energy conversion inside an electrochemical battery during discharge?",
        "option_a": "Chemical energy to Electrical energy",
        "option_b": "Nuclear energy to Heat energy",
        "option_c": "Electrical energy to Chemical energy",
        "option_d": "Kinetic energy to Potential energy",
        "correct_option": "A",
        "category": "Electrical & Physics",
        "difficulty": "Easy",
        "explanation": "Batteries convert stored chemical potential energy into electrical energy."
    },
    {
        "question_text": "What is the primary energy conversion in a photovoltaic solar cell?",
        "option_a": "Thermal energy to Sound energy",
        "option_b": "Light/Solar energy to Electrical energy",
        "option_c": "Chemical energy to Mechanical energy",
        "option_d": "Magnetic energy to Light energy",
        "correct_option": "B",
        "category": "Electrical & Physics",
        "difficulty": "Easy",
        "explanation": "Solar cells convert photons (light) directly into electricity via the photovoltaic effect."
    },
    {
        "question_text": "What electrical conversion is performed by an Inverter?",
        "option_a": "AC to DC",
        "option_b": "DC to AC",
        "option_c": "High AC to Low AC",
        "option_d": "Analog to Digital",
        "correct_option": "B",
        "category": "Electrical & Physics",
        "difficulty": "Easy",
        "explanation": "An inverter converts Direct Current (DC) into Alternating Current (AC)."
    },
    {
        "question_text": "What electrical conversion is performed by a Rectifier circuit?",
        "option_a": "DC to AC",
        "option_b": "AC to DC",
        "option_c": "Mechanical to Electrical",
        "option_d": "Low frequency to High frequency",
        "correct_option": "B",
        "category": "Electrical & Physics",
        "difficulty": "Easy",
        "explanation": "A rectifier converts Alternating Current (AC) into Direct Current (DC)."
    },
    {
        "question_text": "What does UPS stand for in power systems?",
        "option_a": "Universal Power Source",
        "option_b": "Uninterruptible Power Supply",
        "option_c": "Unified Protection Switch",
        "option_d": "Ultra Power Storage",
        "correct_option": "B",
        "category": "Electrical & Physics",
        "difficulty": "Easy",
        "explanation": "UPS stands for Uninterruptible Power Supply."
    },
    {
        "question_text": "What is the primary safety purpose of an electrical fuse?",
        "option_a": "Increase the supply voltage",
        "option_b": "Protect circuits by melting during overcurrent/short-circuit",
        "option_c": "Filter harmonic noise",
        "option_d": "Store reserve electric charge",
        "correct_option": "B",
        "category": "Electrical & Physics",
        "difficulty": "Easy",
        "explanation": "A fuse contains a sacrificial wire that melts when current exceeds a safe threshold."
    },
    {
        "question_text": "Why is electrical earthing (grounding) used in electrical installations?",
        "option_a": "To reduce electricity bill",
        "option_b": "To protect humans and equipment from dangerous shock currents",
        "option_c": "To increase motor speed",
        "option_d": "To step up the AC frequency",
        "correct_option": "B",
        "category": "Electrical & Physics",
        "difficulty": "Easy",
        "explanation": "Earthing provides a low-resistance path to dissipate fault currents safely into the ground."
    },
    {
        "question_text": "Which metal is most widely used for commercial electrical wiring due to high conductivity and ductility?",
        "option_a": "Iron",
        "option_b": "Copper (Cu)",
        "option_c": "Lead",
        "option_d": "Tungsten",
        "correct_option": "B",
        "category": "Materials & Physics",
        "difficulty": "Easy",
        "explanation": "Copper has high electrical conductivity, excellent ductility, and corrosion resistance."
    },
    {
        "question_text": "Which material is the most widely utilized semiconductor in modern microelectronics?",
        "option_a": "Silicon (Si)",
        "option_b": "Copper (Cu)",
        "option_c": "Aluminum (Al)",
        "option_d": "Sulfur (S)",
        "correct_option": "A",
        "category": "Electronics",
        "difficulty": "Easy",
        "explanation": "Silicon is the cornerstone semiconductor material used in ICs and transistors."
    },
    {
        "question_text": "What is the fundamental operational characteristic of a semiconductor Diode?",
        "option_a": "Amplifies input AC voltage",
        "option_b": "Allows current flow in one direction only (unidirectional)",
        "option_c": "Stores magnetic energy",
        "option_d": "Converts mechanical energy into light",
        "correct_option": "B",
        "category": "Electronics",
        "difficulty": "Easy",
        "explanation": "A diode allows current to flow freely in forward bias while blocking reverse current."
    },
    {
        "question_text": "What does LED stand for?",
        "option_a": "Laser Emission Diode",
        "option_b": "Light Emitting Diode",
        "option_c": "Linear Energy Device",
        "option_d": "Low Energy Detector",
        "correct_option": "B",
        "category": "Electronics",
        "difficulty": "Easy",
        "explanation": "LED stands for Light Emitting Diode."
    },
    {
        "question_text": "Which circuit component stores electrical energy in an electrostatic field between two conductive plates?",
        "option_a": "Inductor",
        "option_b": "Capacitor",
        "option_c": "Resistor",
        "option_d": "Transformer",
        "correct_option": "B",
        "category": "Circuit Elements",
        "difficulty": "Easy",
        "explanation": "Capacitors store electrical potential energy in an electrostatic field (E = 0.5*C*V^2)."
    },
    {
        "question_text": "What physical energy conversion does a Microphone perform?",
        "option_a": "Electrical signals to Sound waves",
        "option_b": "Acoustic (sound) energy to Electrical signals",
        "option_c": "Light energy to Heat energy",
        "option_d": "Chemical energy to Kinetic energy",
        "correct_option": "B",
        "category": "Transducers",
        "difficulty": "Easy",
        "explanation": "Microphones are acoustic transducers that convert sound pressure waves into electrical signals."
    },
    {
        "question_text": "What physical conversion does an audio Loudspeaker perform?",
        "option_a": "Sound waves to Electrical signals",
        "option_b": "Electrical signals to Acoustic (sound) waves",
        "option_c": "Thermal energy to Light",
        "option_d": "Digital bits to Analog radio waves",
        "correct_option": "B",
        "category": "Transducers",
        "difficulty": "Easy",
        "explanation": "Loudspeakers convert electrical audio signals into audible mechanical sound vibrations."
    },
    {
        "question_text": "Which scientist discovered the fundamental law of Electromagnetic Induction?",
        "option_a": "Isaac Newton",
        "option_b": "Michael Faraday",
        "option_c": "Albert Einstein",
        "option_d": "James Clerk Maxwell",
        "correct_option": "B",
        "category": "Physics",
        "difficulty": "Easy",
        "explanation": "Michael Faraday discovered electromagnetic induction in 1831."
    },
    {
        "question_text": "What type of physical field is intrinsically generated around any current-carrying electrical conductor?",
        "option_a": "Gravitational field only",
        "option_b": "Magnetic field",
        "option_c": "Nuclear strong field",
        "option_d": "Thermal radiation field only",
        "correct_option": "B",
        "category": "Physics",
        "difficulty": "Easy",
        "explanation": "According to Ampere's law, electric current produces a surrounding magnetic field."
    },
    {
        "question_text": "What is the SI unit of frequency?",
        "option_a": "Becquerel",
        "option_b": "Hertz (Hz)",
        "option_c": "Radian",
        "option_d": "Decibel",
        "correct_option": "B",
        "category": "Physics",
        "difficulty": "Easy",
        "explanation": "Frequency is measured in Hertz (1 Hz = 1 cycle per second)."
    },
    {
        "question_text": "What is the SI unit of electric charge?",
        "option_a": "Ampere",
        "option_b": "Coulomb (C)",
        "option_c": "Volt",
        "option_d": "Ohm",
        "correct_option": "B",
        "category": "Physics",
        "difficulty": "Easy",
        "explanation": "Electric charge is measured in Coulombs (C), where 1 C = 1 A·s."
    },
    {
        "question_text": "How many Watts are equivalent to 1 Kilowatt (kW)?",
        "option_a": "100 W",
        "option_b": "1000 W",
        "option_c": "10,000 W",
        "option_d": "1,000,000 W",
        "correct_option": "B",
        "category": "Physics",
        "difficulty": "Easy",
        "explanation": "1 kW = 1,000 Watts."
    },
    {
        "question_text": "What does CPU stand for in computer science?",
        "option_a": "Central Processing Unit",
        "option_b": "Core Program Utility",
        "option_c": "Control Protocol Unit",
        "option_d": "Computer Power Universal",
        "correct_option": "A",
        "category": "Computer Science",
        "difficulty": "Easy",
        "explanation": "CPU stands for Central Processing Unit."
    },
    {
        "question_text": "What is the primary volatile temporary memory in a computer system?",
        "option_a": "Hard Disk Drive (HDD)",
        "option_b": "RAM (Random Access Memory)",
        "option_c": "ROM (Read Only Memory)",
        "option_d": "Optical Drive",
        "correct_option": "B",
        "category": "Computer Science",
        "difficulty": "Easy",
        "explanation": "RAM is fast, volatile primary memory used by the CPU during program execution."
    },
    {
        "question_text": "How many bits constitute 1 standard Byte?",
        "option_a": "4 bits",
        "option_b": "8 bits",
        "option_c": "16 bits",
        "option_d": "32 bits",
        "correct_option": "B",
        "category": "Computer Science",
        "difficulty": "Easy",
        "explanation": "1 Byte = 8 bits."
    },
    {
        "question_text": "What is a finite step-by-step procedure for solving a computational problem called?",
        "option_a": "Syntax error",
        "option_b": "Algorithm",
        "option_c": "Bandwidth",
        "option_d": "Cache",
        "correct_option": "B",
        "category": "Computer Science",
        "difficulty": "Easy",
        "explanation": "An algorithm is a well-defined sequence of computational steps to solve a problem."
    },
    {
        "question_text": "What does SQL stand for in database management?",
        "option_a": "Standard Query Language",
        "option_b": "Structured Query Language",
        "option_c": "Sequential Query Logic",
        "option_d": "System Quality Layer",
        "correct_option": "B",
        "category": "Computer Science",
        "difficulty": "Easy",
        "explanation": "SQL stands for Structured Query Language."
    },
    {
        "question_text": "What does LAN stand for in computer networking?",
        "option_a": "Local Access Node",
        "option_b": "Local Area Network",
        "option_c": "Logical Array Network",
        "option_d": "Linear Associated Network",
        "correct_option": "B",
        "category": "Computer Science",
        "difficulty": "Easy",
        "explanation": "LAN stands for Local Area Network."
    },
    {
        "question_text": "What does URL stand for in internet technology?",
        "option_a": "Uniform Resource Locator",
        "option_b": "Universal Routing Link",
        "option_c": "Unified Resource Language",
        "option_d": "User Retrieval Link",
        "correct_option": "A",
        "category": "Computer Science",
        "difficulty": "Easy",
        "explanation": "URL stands for Uniform Resource Locator."
    },
    {
        "question_text": "Which blood cells are primarily responsible for transporting oxygen throughout the human body?",
        "option_a": "Platelets (Thrombocytes)",
        "option_b": "Red Blood Cells (Erythrocytes)",
        "option_c": "White Blood Cells (Leukocytes)",
        "option_d": "Lymphocytes",
        "correct_option": "B",
        "category": "Human Biology & BME",
        "difficulty": "Easy",
        "explanation": "Red blood cells contain hemoglobin, which binds and carries oxygen to bodily tissues."
    },
    {
        "question_text": "Which medical instrument records the electrical activity of the human heart?",
        "option_a": "Electroencephalograph (EEG)",
        "option_b": "Electrocardiograph (ECG/EKG)",
        "option_c": "Electromyograph (EMG)",
        "option_d": "Spirometer",
        "correct_option": "B",
        "category": "Human Biology & BME",
        "difficulty": "Easy",
        "explanation": "An ECG records heart depolarization and repolarization potentials."
    },
    {
        "question_text": "Which medical diagnostic instrument records the electrical activity of the human brain?",
        "option_a": "Electrocardiograph (ECG)",
        "option_b": "Electroencephalograph (EEG)",
        "option_c": "Phonocardiograph",
        "option_d": "Goniometer",
        "correct_option": "B",
        "category": "Human Biology & BME",
        "difficulty": "Easy",
        "explanation": "EEG measures post-synaptic electrical oscillations of brain neurons across the scalp."
    },
    {
        "question_text": "Which medical imaging modality utilizes high-frequency acoustic waves beyond 20 kHz?",
        "option_a": "Computed Tomography (CT)",
        "option_b": "Diagnostic Ultrasound (Ultrasonography)",
        "option_c": "Positron Emission Tomography (PET)",
        "option_d": "Fluoroscopy",
        "correct_option": "B",
        "category": "Medical Imaging",
        "difficulty": "Easy",
        "explanation": "Ultrasound relies on piezoelectric transducers emitting sound waves in the 1–20 MHz range."
    },
    {
        "question_text": "What is the primary function of a Pulse Oximeter in clinical practice?",
        "option_a": "Measure body core temperature",
        "option_b": "Measure arterial blood oxygen saturation (SpO2) and pulse rate",
        "option_c": "Detect bone fractures",
        "option_d": "Record brainwave frequencies",
        "correct_option": "B",
        "category": "Medical Devices",
        "difficulty": "Easy",
        "explanation": "Pulse oximeters non-invasively monitor peripheral arterial SpO2 percentage and pulse rate."
    },
    {
        "question_text": "What is the standard unit of measurement for blood pressure in clinical medicine?",
        "option_a": "Bar",
        "option_b": "mmHg (Millimeters of Mercury)",
        "option_c": "PSI (Pounds per square inch)",
        "option_d": "Atmosphere (atm)",
        "correct_option": "B",
        "category": "Human Biology & BME",
        "difficulty": "Easy",
        "explanation": "Clinical blood pressure is expressed in millimeters of mercury (mmHg)."
    },
    {
        "question_text": "What process destroys or eliminates all viable forms of microbial life and spores on medical instruments?",
        "option_a": "Disinfection",
        "option_b": "Sterilization (Autoclaving)",
        "option_c": "Sanitization",
        "option_d": "Pasteurization",
        "correct_option": "B",
        "category": "Human Biology & BME",
        "difficulty": "Easy",
        "explanation": "Sterilization kills 100% of bacterial spores, viruses, and vegetative microorganisms."
    },
    {
        "question_text": "What is the current I supplied by a 12 V voltage source across a single 6 Ω resistor?",
        "option_a": "0.5 A",
        "option_b": "2 A",
        "option_c": "6 A",
        "option_d": "72 A",
        "correct_option": "B",
        "category": "Circuit Problems",
        "difficulty": "Easy",
        "explanation": "By Ohm's Law: I = V / R = 12 V / 6 Ω = 2 A."
    },
    {
        "question_text": "What is the loop current I in a circuit containing a 24 V source feeding 4 Ω and 8 Ω resistors in series?",
        "option_a": "1 A",
        "option_b": "2 A",
        "option_c": "4 A",
        "option_d": "6 A",
        "correct_option": "B",
        "category": "Circuit Problems",
        "difficulty": "Easy",
        "explanation": "R_total = 4 + 8 = 12 Ω. Current I = 24 V / 12 Ω = 2 A."
    },
    {
        "question_text": "What is the total current drawn from a 12 V source connected across parallel 6 Ω and 3 Ω branches?",
        "option_a": "2 A",
        "option_b": "6 A",
        "option_c": "9 A",
        "option_d": "18 A",
        "correct_option": "B",
        "category": "Circuit Problems",
        "difficulty": "Easy",
        "explanation": "R_eq = (6 × 3)/(6 + 3) = 2 Ω. Total Current I = 12 V / 2 Ω = 6 A (or I = 12/6 + 12/3 = 2 + 4 = 6 A)."
    },
    {
        "question_text": "What is the voltage drop across a 3 Ω resistor connected in series with a 2 Ω resistor across a 10 V source?",
        "option_a": "4 V",
        "option_b": "6 V",
        "option_c": "5 V",
        "option_d": "10 V",
        "correct_option": "B",
        "category": "Circuit Problems",
        "difficulty": "Easy",
        "explanation": "By voltage divider: V_3Ω = 10 V × (3 / (2 + 3)) = 10 × (3/5) = 6 V."
    },
    {
        "question_text": "How much electrical power in Watts is dissipated by a 5 Ω resistor connected directly across a 15 V source?",
        "option_a": "3 W",
        "option_b": "45 W",
        "option_c": "75 W",
        "option_d": "1125 W",
        "correct_option": "B",
        "category": "Circuit Problems",
        "difficulty": "Easy",
        "explanation": "Power P = V^2 / R = (15)^2 / 5 = 225 / 5 = 45 W."
    },

    # ==================== MEDIUM LEVEL ====================
    {
        "question_text": "What is the standard nominal AC power supply frequency in Bangladesh?",
        "option_a": "60 Hz",
        "option_b": "50 Hz",
        "option_c": "100 Hz",
        "option_d": "120 Hz",
        "correct_option": "B",
        "category": "Electrical Engineering",
        "difficulty": "Medium",
        "explanation": "The national power grid standard in Bangladesh operates at 50 Hz, 220-230 V single phase."
    },
    {
        "question_text": "What are the two primary functional operations of a semiconductor bipolar junction transistor (BJT)?",
        "option_a": "Rectification and Filtering",
        "option_b": "Amplification and Switching",
        "option_c": "Inversion and Transformation",
        "option_d": "Induction and Capacitance",
        "correct_option": "B",
        "category": "Electronics",
        "difficulty": "Medium",
        "explanation": "Transistors function as linear signal amplifiers and solid-state high-speed electronic switches."
    },
    {
        "question_text": "In what type of physical field does an electrical Inductor store energy?",
        "option_a": "Electrostatic field",
        "option_b": "Magnetic field",
        "option_c": "Gravitational field",
        "option_d": "Nuclear field",
        "correct_option": "B",
        "category": "Circuit Elements",
        "difficulty": "Medium",
        "explanation": "Inductors store energy in the magnetic field created by current flow (W = 0.5*L*I^2)."
    },
    {
        "question_text": "What is the primary technical reason for stepping up AC voltages to ultra-high levels for long-distance power transmission?",
        "option_a": "Increase the frequency of power lines",
        "option_b": "Reduce current, thereby minimizing I^2*R transmission line power losses",
        "option_c": "Make the copper cables lighter in weight",
        "option_d": "Eliminate the need for transformers",
        "correct_option": "B",
        "category": "Electrical Engineering",
        "difficulty": "Medium",
        "explanation": "Stepping up voltage reduces current for the same transmitted power, drastically lowering resistive I^2*R losses."
    },
    {
        "question_text": "What is the ideal numerical value of power factor in an AC electrical power system?",
        "option_a": "0",
        "option_b": "1.0 (Unity)",
        "option_c": "0.5",
        "option_d": "Infinity",
        "correct_option": "B",
        "category": "Electrical Engineering",
        "difficulty": "Medium",
        "explanation": "Unity power factor (cos θ = 1.0) means all power supplied is purely active real power with zero reactive loss."
    },
    {
        "question_text": "What is the SI unit of magnetic flux?",
        "option_a": "Tesla",
        "option_b": "Weber (Wb)",
        "option_c": "Henry",
        "option_d": "Gauss",
        "correct_option": "B",
        "category": "Physics",
        "difficulty": "Medium",
        "explanation": "Magnetic flux is measured in Webers (1 Wb = 1 T·m^2)."
    },
    {
        "question_text": "What is the SI unit of electrical capacitance?",
        "option_a": "Henry",
        "option_b": "Farad (F)",
        "option_c": "Coulomb",
        "option_d": "Siemens",
        "correct_option": "B",
        "category": "Circuit Elements",
        "difficulty": "Medium",
        "explanation": "Capacitance is measured in Farads (1 F = 1 Coulomb per Volt)."
    },
    {
        "question_text": "What is the SI unit of electrical inductance?",
        "option_a": "Tesla",
        "option_b": "Henry (H)",
        "option_c": "Weber",
        "option_d": "Farad",
        "correct_option": "B",
        "category": "Circuit Elements",
        "difficulty": "Medium",
        "explanation": "Inductance is measured in Henries (1 H = 1 Wb/A)."
    },
    {
        "question_text": "How much electrical energy in kWh is consumed by a 2 kW electric heater running continuously for 3 hours?",
        "option_a": "1.5 kWh",
        "option_b": "6 kWh",
        "option_c": "5 kWh",
        "option_d": "12 kWh",
        "correct_option": "B",
        "category": "Electrical Engineering",
        "difficulty": "Medium",
        "explanation": "Energy = Power × Time = 2 kW × 3 hours = 6 kWh."
    },
    {
        "question_text": "Which fundamental computer science data structure operates strictly on a Last-In, First-Out (LIFO) order?",
        "option_a": "Queue",
        "option_b": "Stack",
        "option_c": "Binary Search Tree",
        "option_d": "Linked List",
        "correct_option": "B",
        "category": "Computer Science",
        "difficulty": "Medium",
        "explanation": "A Stack operates on LIFO principles, where push and pop occur at the top."
    },
    {
        "question_text": "Which data structure is typically implemented in software applications to support the 'Undo' operation?",
        "option_a": "Queue (FIFO)",
        "option_b": "Stack (LIFO)",
        "option_c": "Priority Heap",
        "option_d": "Hash Table",
        "correct_option": "B",
        "category": "Computer Science",
        "difficulty": "Medium",
        "explanation": "The 'Undo' operation reverses recent actions in reverse chronological order using a Stack."
    },
    {
        "question_text": "What is the decimal equivalent of the 3-bit unsigned binary number 101?",
        "option_a": "3",
        "option_b": "5",
        "option_c": "6",
        "option_d": "7",
        "correct_option": "B",
        "category": "Computer Science",
        "difficulty": "Medium",
        "explanation": "1×(2^2) + 0×(2^1) + 1×(2^0) = 4 + 0 + 1 = 5."
    },
    {
        "question_text": "Which medical device performs extracorporeal waste filtering and fluid removal during acute or chronic kidney failure?",
        "option_a": "Spirometer",
        "option_b": "Hemodialyzer (Hemodialysis Machine)",
        "option_c": "Autoclave",
        "option_d": "Defibrillator",
        "correct_option": "B",
        "category": "Medical Devices",
        "difficulty": "Medium",
        "explanation": "Hemodialysis filters waste products like urea and creatinine from blood when kidneys fail."
    },
    {
        "question_text": "What is an artificial mechanical replacement for an anatomically missing human limb called?",
        "option_a": "Orthosis",
        "option_b": "Prosthesis (Prosthetic Limb)",
        "option_c": "Stent",
        "option_d": "Dialyzer",
        "correct_option": "B",
        "category": "Biomedical Engineering",
        "difficulty": "Medium",
        "explanation": "A prosthesis replaces a missing body part, whereas an orthosis supports an existing body part."
    },
    {
        "question_text": "What surgically implanted auditory prosthesis directly stimulates the cochlear auditory nerve fibers to restore hearing sensation?",
        "option_a": "Acoustic Hearing Aid",
        "option_b": "Cochlear Implant",
        "option_c": "Tympanic Membrane Tube",
        "option_d": "Bone Conduction Headband",
        "correct_option": "B",
        "category": "Medical Devices",
        "difficulty": "Medium",
        "explanation": "Cochlear implants bypass damaged hair cells to electrically stimulate auditory nerve endings directly."
    },
    {
        "question_text": "What essential biomaterial property ensures that an implant causes no toxic, injurious, or adverse immune reaction in vivo?",
        "option_a": "Superconductivity",
        "option_b": "Biocompatibility",
        "option_c": "Ferromagnetism",
        "option_d": "High Piezoelectricity",
        "correct_option": "B",
        "category": "Biomaterials",
        "difficulty": "Medium",
        "explanation": "Biocompatibility is the ability of a material to perform with an appropriate host response in a specific application."
    },
    {
        "question_text": "Which MEMS motion sensor is embedded inside smartwatches to track daily step counts and body motion?",
        "option_a": "Thermopile sensor",
        "option_b": "3-Axis Accelerometer / IMU",
        "option_c": "Galvanic Galvanometer",
        "option_d": "pH Electrode",
        "correct_option": "B",
        "category": "Biosensors",
        "difficulty": "Medium",
        "explanation": "Tri-axial MEMS accelerometers measure dynamic acceleration to detect gait and step counts."
    },
    {
        "question_text": "Upon which fundamental law of fluid mechanics do hydraulic brake systems and hydraulic lifts operate?",
        "option_a": "Bernoulli's Principle",
        "option_b": "Pascal's Law",
        "option_c": "Archimedes' Principle",
        "option_d": "Hooke's Law",
        "correct_option": "B",
        "category": "Mechanical & Fluid Mechanics",
        "difficulty": "Medium",
        "explanation": "Pascal's Law states that pressure applied to an enclosed incompressible fluid is transmitted undiminished in all directions."
    },
    {
        "question_text": "What material property describes the capacity of a solid metal to undergo plastic deformation and be drawn into thin wires without rupturing?",
        "option_a": "Brittleness",
        "option_b": "Ductility",
        "option_c": "Hardness",
        "option_d": "Stiffness",
        "correct_option": "B",
        "category": "Materials Engineering",
        "difficulty": "Medium",
        "explanation": "Ductility is the ability of a solid material to deform under tensile stress into wires."
    },
    {
        "question_text": "Which glycoprotein hormone secreted primarily by the adult kidneys stimulates bone marrow to produce red blood cells?",
        "option_a": "Insulin",
        "option_b": "Erythropoietin (EPO)",
        "option_c": "Thyroxine",
        "option_d": "Adrenaline",
        "correct_option": "B",
        "category": "Physiology",
        "difficulty": "Medium",
        "explanation": "Erythropoietin (EPO) is released by peritubular kidney cells in response to cellular hypoxia."
    },
    {
        "question_text": "In a bridge circuit with resistors 2 Ω, 3 Ω, 4 Ω, and 6 Ω driven by a 12 V source, what is the current Ix through the central 5 Ω detector branch?",
        "option_a": "2 A",
        "option_b": "0 A (Balanced Bridge)",
        "option_c": "1.2 A",
        "option_d": "0.5 A",
        "correct_option": "B",
        "category": "Circuit Problems",
        "difficulty": "Medium",
        "explanation": "Since (2 Ω / 4 Ω) = (3 Ω / 6 Ω) = 0.5, the Wheatstone bridge is perfectly balanced and Ix = 0 A."
    },
    {
        "question_text": "What is the net loop current when a 20 V source opposes an 8 V source across 4 Ω and 2 Ω series resistors?",
        "option_a": "1 A",
        "option_b": "2 A",
        "option_c": "4.67 A",
        "option_d": "3 A",
        "correct_option": "B",
        "category": "Circuit Problems",
        "difficulty": "Medium",
        "explanation": "Net Voltage = 20 - 8 = 12 V. Total Resistance = 4 + 2 = 6 Ω. Current I = 12 V / 6 Ω = 2 A."
    },
    {
        "question_text": "What is the node voltage V across parallel 4 Ω and 12 Ω resistors driven by a 6 A ideal current source?",
        "option_a": "12 V",
        "option_b": "18 V",
        "option_c": "24 V",
        "option_d": "36 V",
        "correct_option": "B",
        "category": "Circuit Problems",
        "difficulty": "Medium",
        "explanation": "Req = (4 × 12) / (4 + 12) = 48 / 16 = 3 Ω. Node voltage V = 6 A × 3 Ω = 18 V."
    },

    # ==================== HARD LEVEL ====================
    {
        "question_text": "Why do electrical power transformers operate exclusively on time-varying AC current and fail to function on steady DC current?",
        "option_a": "DC causes infinite resistance in copper coils",
        "option_b": "Transformers require a time-varying magnetic flux (dΦ/dt != 0) to induce EMF by Faraday's Law; steady DC produces zero flux change",
        "option_c": "AC produces electrostatic charges whereas DC does not",
        "option_d": "DC frequency is too high for iron cores",
        "correct_option": "B",
        "category": "Electromagnetic Theory",
        "difficulty": "Hard",
        "explanation": "Faraday's Law states induced EMF is proportional to the rate of change of magnetic flux (e = -N dΦ/dt). Steady DC yields dΦ/dt = 0."
    },
    {
        "question_text": "What biomedical apparatus is externally applied to support, align, stabilize, or correct the biomechanical function of an intact anatomical body part?",
        "option_a": "Prosthesis",
        "option_b": "Orthosis (Orthotic Device / Brace)",
        "option_c": "Stent Graft",
        "option_d": "Dialyzer",
        "correct_option": "B",
        "category": "Biomechanics & Rehabilitation",
        "difficulty": "Hard",
        "explanation": "An Orthosis supports and aligns existing body segments, distinct from a Prosthesis which substitutes for a missing segment."
    },
    {
        "question_text": "What is the structural and biological function of a 3D porous biomimetic scaffold in regenerative tissue engineering?",
        "option_a": "Block all nutrient diffusion to isolate cells",
        "option_b": "Provide an extracellular matrix template for cell attachment, proliferation, vascular ingrowth, and new tissue synthesis",
        "option_c": "Prevent cell differentiation into mature tissue",
        "option_d": "Permanently replace bone without bio-resorption",
        "correct_option": "B",
        "category": "Tissue Engineering",
        "difficulty": "Hard",
        "explanation": "Scaffolds mimic native extracellular matrix (ECM), providing mechanical support and porosity for cellular infiltration and neovascularization."
    },
    {
        "question_text": "How are modern myoelectric active upper-limb prostheses controlled by an amputee?",
        "option_a": "Through brain implant surgery only",
        "option_b": "By acquiring electromyographic (EMG) surface potentials generated during residual muscle contractions",
        "option_c": "Using mechanical body-powered shoulder harnesses",
        "option_d": "Voice recognition microphones embedded in the socket",
        "correct_option": "B",
        "category": "Biomedical Instrumentation",
        "difficulty": "Hard",
        "explanation": "Surface EMG sensors pick up microvolt muscle action potentials from the residual stump to actuate motorized fingers/wrist."
    },
    {
        "question_text": "What is the primary underlying structural mechanism that leads to mechanical fatigue failure in engineering materials under cyclic loading?",
        "option_a": "Instantaneous ductile yielding across the entire cross-section",
        "option_b": "Progressive microscopic crack initiation and cyclic subcritical crack growth leading to catastrophic final fracture",
        "option_c": "Uniform thermal expansion beyond melting point",
        "option_d": "Chemical decomposition of metallic bonds",
        "correct_option": "B",
        "category": "Materials Science",
        "difficulty": "Hard",
        "explanation": "Fatigue occurs under repeated stress cycles below yield strength due to localized micro-crack nucleation and progressive striation growth."
    },
    {
        "question_text": "Which major functional and anatomical division of the human brain is primarily responsible for conscious cognition, abstract reasoning, and voluntary motor execution?",
        "option_a": "Cerebellum",
        "option_b": "Cerebral Cortex (Cerebrum)",
        "option_c": "Medulla Oblongata",
        "option_d": "Pons",
        "correct_option": "B",
        "category": "Physiology & Neuroengineering",
        "difficulty": "Hard",
        "explanation": "The cerebral cortex mediates executive cognitive planning, sensory perception, abstract reasoning, and voluntary movements."
    },
    {
        "question_text": "In a dual-opposing current source parallel network containing two 60 Ω resistors and opposing 9 A (upward) and 6 A (downward) sources, what is the node voltage Vx?",
        "option_a": "30 V",
        "option_b": "90 V",
        "option_c": "180 V",
        "option_d": "450 V",
        "correct_option": "B",
        "category": "Circuit Problems",
        "difficulty": "Hard",
        "explanation": "Net upward injected current I_net = 9 A - 6 A = 3 A. Equivalent resistance R_eq = 60 Ω || 60 Ω = 30 Ω. Voltage Vx = 3 A × 30 Ω = 90 V."
    },
    {
        "question_text": "What optical principle enables Photoplethysmography (PPG) sensors to measure cardiac pulse and arterial volume changes?",
        "option_a": "Detection of optical Doppler frequency shift from sound waves",
        "option_b": "Measurement of light attenuation variations corresponding to pulsatile blood volume fluctuations in the microvascular bed",
        "option_c": "Nuclear magnetic resonance of hydrogen nuclei",
        "option_d": "Total internal reflection inside bone marrow",
        "correct_option": "B",
        "category": "Biosensors & Instrumentation",
        "difficulty": "Hard",
        "explanation": "PPG shines LED light (typically green or red/IR) into skin and detects transmitted/reflected light variations caused by pulsatile capillary expansion."
    }
]
